 <?php 	
	//ini_set('default_charset', 'UTF-8');
	$language = get_option("WPLANG");
	if($language == "en_US"){
			define("CATEGORYDIV","Select a menu.");
			define("TITLEDIV","This field is required.");
			define("POSITIONDIV","Select your article position.");
			define("CAPTCHAEDIV","Please enter captcha value.");
			define("CAPTCHACODE","CAPTCHA Code");
			define("ARTICLECREATED","Article created");	
			define("ARTICLEEXISTS","Article already exists");	
			define("ARTICLEUPDATED","Article updated");	
			define("ARTICLEDELETEDHEADER","The article has been deleted.");
			define("ARTICLEDELETED","has been deleted.");
			define("MINUTESAGO","minutes ago");
			define("HOURSAGO","hours ago");		
			define("HOME","Home");
			define("NOARTICLEFOUND","No article found");
			define("REGISTERPART1","You may write an article on this site as an unregistered contributor or you could register");	
			define("REGISTEREDCONTRIBUTOR","Registered Contributor");
			define("HERE","here");
			define("ARTICLEREVIEW","The article is ready for review.");
			define("OK","OK");
			define("ARTICLESUBMITTED","Your article has been submitted");
			define("ARTICLESUBMITTEDSUB","Your article will now be reviewed by our editorial staff.");
			define("ARTICLESUBMITTEDSUB1","If approved, your article will be posted shortly.");
			define("ERROROCCURED","An error has occured");
			define("ERROROCCUREDSUB","We were not able to register your article");
			define("ERROROCCUREDSUB1","Please try again later.");
			define("ERROROCCUREDSUB2","Please enter another article.");
			define("IMAGEUPLOADSTATUSBAR","Please wait,loading image.....");
			define("DESCRIPTIONDIV","Please add article (body) text.");
			define("IMAGEDIV","Please upload image.");
			define("SAVEDRAFT","Save Draft");
			define("SUBMIT","Submit");
			define("ILLEGALACCESS","You don't have permission to access.");
			define("INVALIDCAPTCHADIV","Please enter valid captcha value.");
			define("CONFIRMDELETE","Do you want to delete this article?");
			define("ARTICLESELECTION","Please select the article");
			define("PUAIN", "Publish your own article in");
			define("PIN", "Publish in");
			define("LOGIN", "Login");
			define("REGISTER", "Register");
			define("LOGOUT", "Logout");
			define("YAHBP", "Your article has been published.");
			define("LASUOA", "Like and share your own article!");
			define("YAHBSTOM", "Your article has been sent to our moderators.");
			define("CBSTSYPA", "Check back soon to see your published article!");
			define("PUBLISH", "PUBLISH");

	}else if($language == "sv_SE"){
			define("CATEGORYDIV","V&auml;lj en meny.");
			define("TITLEDIV","Detta f&auml;lt &auml;r obligatoriskt.");
			define("POSITIONDIV","V&auml;lj hur du vill placera artikeln.");
			define("CAPTCHAEDIV","Ange captcha kod.");
			define("CAPTCHACODE","CAPTCHA kod");
			define("ARTICLECREATED","Artikel sparade");
			define("ARTICLEEXISTS","Artikel finns redan");
			define("ARTICLEUPDATED","Artikel uppdaterad");
			define("ARTICLEDELETED","har raderats.");
			define("ARTICLEDELETEDHEADER","Artikeln har tagits bort.");
			define("MINUTESAGO","minuter sedan");
			define("HOURSAGO","timmar sedan");
			define("HOME","Hem");
			define("NOARTICLEFOUND","Ingen artikel hittades");
			define("REGISTERPART1","Du kan skriva en artikel p&aring; denna webbplats som en oregistrerad bidragsgivare eller du kan registrera");	
			define("REGISTEREDCONTRIBUTOR","Registrerad inl&auml;ggsskribent");
			define("HERE","h&auml;r");
			define("ARTICLEREVIEW","Artikeln &auml;r redo f&ouml;r utv&auml;rdering.");
			define("OK","OK");
			define("ARTICLESUBMITTED","Din artikel har skickats");
			define("ARTICLESUBMITTEDSUB","Din artikel kommer nu att granskas av v&aring;r redaktion.");
			define("ARTICLESUBMITTEDSUB1","Om det godk&auml;nns, kommer din artikel att publiceras inom kort.");
			define("ERROROCCUREDSUB2","Skapa en ny artikel.");
			define("ERROROCCURED","Ett fel har uppst&aring;tt");
			define("ERROROCCUREDSUB","Vi kunde inte registrera din artikel");
			define("ERROROCCUREDSUB1","F&ouml;rs&ouml;k igen senare.");
			define("IMAGEUPLOADSTATUSBAR","V&auml;nta, h&auml;mtar bilden.....");
			define("DESCRIPTIONDIV","V&auml;nligen l&auml;gg text i artikeln.");
			define("IMAGEDIV","H&auml;mta din bild.");
			define("SAVEDRAFT","Spara utkast");
			define("SUBMIT","Skicka");
			define("ILLEGALACCESS","Du inte har till&aring;telse att komma &aring;t.");
			define("INVALIDCAPTCHADIV","Ange ett giltigt captcha v&auml;rde.");
			define("CONFIRMDELETE","Vill du radera den h&auml;r artikeln?");
			define("ARTICLESELECTION","V&auml;lj artikeln");
			define("PUAIN", "Publicera din egen artikel i");
			define("PIN", "publicera i");
			define("LOGIN", "Logga in");
			define("REGISTER", "Registrera");
			define("LOGOUT", "Logga ut");
			define("YAHBP", "Din artikel har publicerats .");
			define("LASUOA", "Gillar och dela din egen artikel !");
			define("YAHBSTOM", "Din artikel har skickats till våra moderatorer .");
			define("CBSTSYPA", "Återkom snart att se den publicerade artikeln !");
			define("PUBLISH", "PUBLICERA");

	}elseif($language == "nb_NO"){
			define("CATEGORYDIV","Velg en meny.");
			define("TITLEDIV","Dette feltet er p&aring;krevd.");
			define("POSITIONDIV","Velg hvor artikkelen skal plasseres.");
			define("CAPTCHAEDIV","Vennligst oppig captcha kode.");
			define("CAPTCHACODE","CAPTCHA kode");
			define("ARTICLECREATED","Artikkel lagret");
			define("ARTICLEEXISTS","Artikkelen eksisterer allerede");
			define("ARTICLEUPDATED","Artikkelen er oppdatert");	
			define("ARTICLEDELETED","er slettet.");
			define("ARTICLEDELETEDHEADER","Artikkelen er slettet.");
			define("MINUTESAGO","minutter siden");
			define("HOURSAGO","timer siden");
			define("HOME","Hjem");
			define("NOARTICLEFOUND","Ingen artikler registrert");
			define("REGISTERPART1","Du kan skrive en artikkel p&auml; dette nettstedet selv om du ikke registerer deg");	
			define("REGISTEREDCONTRIBUTOR","Registrert bruker");
			define("HERE","her");
			define("ARTICLEREVIEW","Denne artikkelen er klar til gjennomsyn");
			define("OK","OK");
			define("ARTICLESUBMITTED","Artikkelen din har blitt sendt");
			define("ARTICLESUBMITTEDSUB","Artikkelen vil n&aring; bli gjennomg&aring;tt av redaksjonen");
			define("ARTICLESUBMITTEDSUB1","Om den godkjennes, vil den om kort tid bli publisert.");
			define("ERROROCCURED","En feil har oppst&aring;tt");
			define("ERROROCCUREDSUB","Vi klarte ikke &aring; f&aring; registrert artikkelen din.");
			define("ERROROCCUREDSUB1","Pr&oslash;v igjen senere");
			define("ERROROCCUREDSUB2","Skriv en ny artikkel.");
			define("IMAGEUPLOADSTATUSBAR","Vent mens bildet lastes opp..... ");
			define("DESCRIPTIONDIV","Husk &aring; legge inn artikkeltexten.");
			define("IMAGEDIV","Du m&aring; laste opp et bilde til artikkelen.");
			define("SAVEDRAFT","Lagre kladd");
			define("SUBMIT","Send");
			define("ILLEGALACCESS","Du har ikke tillatelse til &aring; f&aring; tilgang.");
			define("INVALIDCAPTCHADIV","Oppgi gyldig captcha kode.");
			define("CONFIRMDELETE","&Oslash; nsker du &aring; slette denne artikkelen?");
			define("ARTICLESELECTION","Vennligst velg artikkelen");
			define("PUAIN", "Publiser din egen artikkel i");
			define("PIN", "publisere i");
			define("LOGIN", "Logg inn");
			define("REGISTER", "Registrere");
			define("LOGOUT", "Logg ut");
			define("YAHBP", "Din artikkelen har blitt publisert.");
			define("LASUOA", "Liker og dele din egen artikkel !");
			define("YAHBSTOM", "Artikkelen din har blitt sendt til våre moderatorer .");
			define("CBSTSYPA", "Kom snart tilbake for å se den publiserte artikkelen!");
			define("PUBLISH", "PUBLISERE");

	}else{
			define("CATEGORYDIV","Select a menu.");
			define("TITLEDIV","This field is required.");
			define("POSITIONDIV","Select your article position.");
			define("CAPTCHAEDIV","Please enter captcha value.");
			define("CAPTCHACODE","CAPTCHA Code");
			define("ARTICLECREATED","Article created");
			define("ARTICLEEXISTS","Article already exists");
			define("ARTICLEUPDATED","Article updated");	
			define("ARTICLEDELETED","has been deleted.");
			define("ARTICLEDELETEDHEADER","The article has been deleted.");
			define("MINUTESAGO","minutes ago");
			define("HOURSAGO","hours ago");
			define("HOME","Home");
			define("NOARTICLEFOUND","No article found");
			define("REGISTERPART1","You may write an article on this site as an unregistered contributor or you could register");
			define("REGISTEREDCONTRIBUTOR","Registered Contributor");
			define("HERE","here");
			define("ARTICLEREVIEW","The article is ready for review.");
			define("OK","OK");
			define("ARTICLESUBMITTED","Your article has been submitted");
			define("ARTICLESUBMITTEDSUB","Your article will now be reviewed by our editorial staff.");
			define("ARTICLESUBMITTEDSUB1","If approved, your article will be posted shortly.");
			define("ERROROCCURED","An error has occured");
			define("ERROROCCUREDSUB","We were not able to register your article");
			define("ERROROCCUREDSUB1","Please try again later.");
			define("ERROROCCUREDSUB2","Please enter another article.");
			define("IMAGEUPLOADSTATUSBAR","Please wait,loading image.....");
			define("DESCRIPTIONDIV","Please add article (body) text.");
			define("IMAGEDIV","Please upload image.");
			define("SAVEDRAFT","Save Draft");
			define("SUBMIT","Submit");
			define("ILLEGALACCESS","You don't have permission to access.");
			define("INVALIDCAPTCHADIV","Please enter valid captcha value.");
			define("CONFIRMDELETE","Do you want to delete this article?");
			define("ARTICLESELECTION","Please select the article");
			define("PUAIN", "Publish you article in");
			define("PIN", "Publish in");
			define("LOGIN", "Login");
			define("REGISTER", "Register");
			define("LOGOUT", "Logout");
			define("YAHBP", "Your article has been published.");
			define("LASUOA", "Like and share your own article!");
			define("YAHBSTOM", "Your article has been sent to our moderators.");
			define("CBSTSYPA", "Check back soon to see your published article!");
			define("PUBLISH", "PUBLISH");
	}
	 